// import naive from 'naive-ui'
import {
    // create naive ui
    create,
    // component
    NButton,
    NLoadingBarProvider,
    NMessageProvider,
    NSpace,
    NLayout,
    NLayoutHeader,
    NMenu,
    NLayoutContent,
    NGrid,
    NGridItem,
    NCard,
    NCarousel,
    NSkeleton,
    NGradientText,
    NImage,
    NBackTop,
    NLayoutFooter,
    NSwitch,
    NIcon,
    NAvatar,
    NDivider,
    NTabs,
    NTabPane,
    NForm,
    NFormItemRow,
    NInput,
    NScrollbar,
    NLayoutSider,
    NDropdown,
    NTooltip,
    NPopover,
    NFormItem,
    NTag,
    NSelect,
    NModal,
    NSpin,
    NDataTable,
  } from 'naive-ui'
  
  const naive = create({
    components: [
      NButton,
      NLoadingBarProvider,
      NMessageProvider,
      NSpace,
      NLayout,
      NLayoutHeader,
      NMenu,
      NLayoutContent,
      NGrid,
      NGridItem,
      NCard,
      NCarousel,
      NSkeleton,
      NGradientText,
      NImage,
      NBackTop,
      NLayoutFooter,
      NSwitch,
      NIcon,
      NAvatar,
      NDivider,
      NTabs,
      NTabPane,
      NForm,
      NFormItemRow,
      NInput,
      NScrollbar,
      NLayoutSider,
      NDropdown,
      NTooltip,
      NPopover,
      NFormItem,
      NTag,
      NSelect,
      NModal,
      NSpin,
      NDataTable,
    ]
  })

  export default naive;